name               = "OnlinePortfolioSelection"
uuid               = "038f9fe3-14bd-47ca-b081-2e00e8c46dfa"
authors            = ["Shayan Davoodi"]
version            = "2.11.0"

[deps]
DataStructures     = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distances          = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Ipopt              = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP               = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra      = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools    = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Statistics         = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase          = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
Clustering         = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Distributions      = "31c24e10-a181-5473-b8eb-7969acd0382f"
HypothesisTests    = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"

[extensions]
CWMRModelExt       = "Distributions"
ClusLogModelExt    = "Clustering"
HypothesisTestsExt = "HypothesisTests"

[compat]
Clustering         = "0.15.7"
DataStructures     = "0.18"
HypothesisTests    = "0.11.0"
Distances          = "0.10"
Distributions      = "0.25.0"
StatsBase          = "0.34.2"
Ipopt              = "1.2"
JuMP               = "1.10"
LinearAlgebra      = "1"
PrecompileTools    = "1.1"
Statistics         = "1"
julia              = "1.9"

[extras]
Test               = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test               = ["Test"]
